schema_version: 20180708
name: bloodpressure_sensor
version: 0.0.1
runtime: go
entrypoint: ./func
format: http-stream
triggers:
- name: bloodpressure_sensor-trigger
  type: http
  source: /bloodpressure_sensor-trigger
